### PR TITLE
Improved performance

### PR DESCRIPTION
**Pull request by Amjad50**
Methods to improve performance

Trying to improve further

### CODE REVIEW

**Comment by Amjad50** [comment]
I think this is a good improvement, we can do better, but we would need to change hound, as the slowness right now is from hound reading samples.

Encode:
image

Decode:
image


As you can see, most of the time is spent on reading the samples, for encoding, its 50/50 between reading from hound and writing to the file, so I think its okay.

But we can make this very fast by using a simple wav writer, and we can do optimization when reading/writing

**Review by TheAwiteb — APPROVED** [review]
Thank you @Amjad50 for this useful improvement

**Comment by TheAwiteb** [comment]
> But we can make this very fast by using a simple wav writer, and we can do optimization when reading/writing

I'll check it

**Comment by Amjad50** [comment]
Another interesting detail/cheat, we can do this extremely easily and make it insanely fast.

the wav file stores the PCM samples directly as bytes, without any compression, so it means the file content are actually stored in bytes, and this is true, as u can see here.

original file
image

wav
image

So we can add just a header for wav and just copy the whole file, which should be fast

**Comment by TheAwiteb** [comment]
> So we can add just a header for wav and just copy the whole file, which should be fast

Wow, is that really possible!! How can we get the header? Is it the same in all files or does it change?

**Comment by Amjad50** [comment]
Hound uses this library: https://docs.rs/wav/latest/wav/index.html

this library allows u to write the header, so yeah, would be interesting to try.

The header looks like it has basic info, like filesize, sample rate, format, etc....

**Pull request merged**
